# Generated by Django 4.2.4 on 2023-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='buyed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
